# GoReleaser configuration for Post-Quantum PKI (QPKI)
# Documentation: https://goreleaser.com

version: 2

project_name: qpki

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: qpki
    main: ./cmd/qpki
    binary: qpki
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: remiblancher
    name: post-quantum-pki
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Quick Install

    **macOS (Homebrew):**
    ```bash
    brew tap remiblancher/qpki && brew install qpki
    ```

    **Linux/macOS (binary):** Download from assets below ⬇️

    **From source:**
    ```bash
    go install github.com/remiblancher/post-quantum-pki/cmd/qpki@v{{.Version}}
    ```

    ---

    ## Changelog

# Linux packages (.deb, .rpm)
nfpms:
  - id: packages
    package_name: qpki
    vendor: Remi Blancher
    homepage: "https://github.com/remiblancher/post-quantum-pki"
    maintainer: "Remi Blancher"
    description: "Post-Quantum PKI (QPKI) - Certificate Authority toolkit supporting classical and Post-Quantum Cryptography (PQC)"
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    priority: optional

# Homebrew tap (macOS)
brews:
  - repository:
      owner: remiblancher
      name: homebrew-qpki
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/remiblancher/post-quantum-pki"
    description: "Post-Quantum PKI (QPKI) - Certificate Authority toolkit with PQC support"
    license: "Apache-2.0"
    install: |
      bin.install "qpki"
    test: |
      system "#{bin}/qpki", "--version"
