coverage:
  precision: 2
  round: down
  range: "45...80"

  status:
    project:
      default:
        target: 50%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
